### PR TITLE
GH-243: SessionInfo virtual destructor

### PR DESCRIPTION
**Pull request by Yanpas**

### CODE REVIEW

**Comment by vlevendel** [comment]
@Yanpas, Please sign and return a Contributor agreement found at https://github.com/Refinitiv/Elektron-SDK and email to [sdkagreement@lseg.com](mailto:sdkagreement@lseg.com)

**Comment by Yanpas** [comment]
Signed and sent

**Comment by vlevendel** [comment]
@Yanpas Apologies. Please resend to this address instead: sdkagreement@refinitiv.com

**Comment by Yanpas** [comment]
> @Yanpas Apologies. Please resend to this address instead: [sdkagreement@refinitiv.com](mailto:sdkagreement@refinitiv.com)

Done

**Pull request merged**
